config/routes.rb
Newstumweb::Application.routes.draw do

  resources :teams do
    resources :users
  end

  resources :users do
    get "new_message", :on => :collection
    post "create_message", :on => :collection
    delete "destroy_message", :on => :collection

    member do
      get 'likes'
      get 'dislikes'
      get 'messages'
      get 'inbox'
      get 'outbox'
      get 'show_message'
    end
  end

  resources :users do
    resources :comments
      end
  resources :sessions, :only => [:new, :create, :destroy]
  resources :photos do
    member do
      get 'like'
      get 'dislike'
    end
  end

  resources :password_resets

  resources :photos do
    resources :comments do
     get 'reply', :on => :collection
   end
 end

  resources :contents do
    member do
      get 'like'
      get 'dislike'
    end
  end

  resources :contents do
    resources :comments do
     get 'reply', :on => :collection
   end
 end

 resources :comments do
  member do
    get 'like'
    get 'dislike'
  end
end

  resources :photos do
    resources :captions 
  end

  root :to => "pages#home"

  match '/contact', :to => 'pages#contact'
  match '/about', :to => 'pages#about'
  match '/help', :to => 'pages#help'
  match '/contest', :to => 'pages#contest'
  match '/bestfeatures', :to => 'pages#bestfeatures'
  match '/index', :to => 'users#index'
  match '/signup', :to => 'users#new'
  match '/signin', :to => 'sessions#new'
  match '/sessions', :to => 'sessions#create'
  match '/signout', :to => 'sessions#destroy'
  match '/comments', :to => 'comments#create'
  match '/contents', :to => 'contents#index'
  match '/contents/:id', :to => 'contents#show'
  match '/contents/:content_id/comments', :to => 'comments#index'
  match '/photos/:photo_id/comments', :to => 'comments#index'
  match '/contents/:content_id/comments/reply', :to => 'comments#reply'
  match '/results', :to => 'contents#index'
  match '/newteam', :to => 'teams#new'
  match '/jointeam', :to => 'teams#join'

end

app/models/content.rb
class Content < ActiveRecord::Base
  acts_as_votable
  is_impressionable :counter_cache => { :column_name => :impressions_count, :unique => true }
  
  attr_accessible :content, :content_changed_at #, :captions_attributes

  before_create :init_sort_column

  after_update :update_user_score
  after_destroy :update_user_score

  belongs_to :user
  has_many :comments, as: :commentable, :dependent => :destroy 
  #has_many :captions, :dependent => :destroy
  #accepts_nested_attributes_for :captions

  #include PgSearch
  #multisearchable :against => :content
  
  validates :content, :presence => true, :length => { :maximum => 50000 }   # spam protection
  #:allow_blank => true is needed to be able to upload images
  #validates :image, :presence => true
  validates :user_id, :presence => true
  
  default_scope :order => 'contents.created_at DESC'

  def self.search(search)
    if search
      find(:all, :conditions => ['content LIKE ?', "%#{search}%"])
    else
      find(:all)
    end
  end

  private

  def init_sort_column
    self.content_changed_at = self.created_at || Time.now
  end

  def update_user_score
    if self.user
      user = self.user
      everything = user.contents + user.photos
      likes_count = everything.inject(0) {|sum, f| sum + f.likes.count}
      dislikes_count = everything.inject(0) {|sum, f| sum + f.dislikes.count}
      unique_views = everything.inject(0) {|sum, f| sum + f.impressionist_count}
      score = ((2 * unique_views) + (likes_count - dislikes_count))
      user.update_column(:score, score)

      if user.team
        team = user.team
        teammates = team.users
        teamscore = teammates.inject(0) {|sum, f| sum + f.score}
        team.update_column(:team_score, teamscore) 
      end
    end
  end
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  before_filter :authenticate, :except => :show
  before_filter :authorized_user, :only => :destroy
  impressionist :actions => [:show], :unique => [:impressionable_type, :impressionable_id, :session_hash]

  def home
    @title = "Home"
      if signed_in?
        @content = content.new
        @feed_items = content.all #.paginate(:page => params[:page])
      end
      if signed_out?
        @feed_items = content.all #.paginate(:page => params[:page])
      end
  end

  def index
    @results = Content.search(params[:search])
  end

  def like
    @user = current_user
    @content = Content.find(params[:id])
    @user.likes @content

    redirect_to root_path
  end

  def dislike
    @user = current_user
    @content = Content.find(params[:id])
    @user.dislikes @content

    redirect_to root_path
  end

  def new 
    @content = Content.new
    @content.captions.build
  end

  def show
    @content = Content.find(params[:id])
    @topcomments = @content.comments.sort_by(&:cached_votes_up).last(4).shuffle.last(2)
    @comments = @content.comments.sort_by(&:created_at).reverse.paginate(page: params[:page], :per_page => 7)
  end

  def create
    @content = current_user.contents.build(params[:content])
    if @content.save
      redirect_to root_path, :flash => { :success => "content created!" }
    else
      redirect_to root_path
    end
  end

  def destroy
      @content.destroy
      redirect_to root_path, :flash => { :success => "content deleted!" }
  end
  
  private
  
    def authorized_user
      if current_user.admin?
        @content = Content.find(params[:id])
        @content.destroy
        redirect_to root_path, :flash => { :success => "content deleted!" }
      else
        @content = current_user.contents.find_by_id(params[:id])
        redirect_to root_path if @content.nil?
      end
    end
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/views/contents/_comments.html.erb
<% @comments.each do |comment| %>

<% if (comment.dislikes.count - comment.likes.count) > 2 %>

    <table class="microposts" summary="User microposts">

<tr>
  <td class="micropost">

  <% if is_mobile_view? %>
  <span class="content" style="width: 125%;"><% if comment.user == @content.user %><b style="color:blue;"><i>This comment is hidden due to too many dislikes.</i></b> <% else %> <b style="color:darkblue;"><i>This comment is hidden due to too many dislikes.</i></b> <% end %></span>
<br>
  <span class="timestamp" style="width: 130%;">
      Posted <%= time_ago_in_words(comment.created_at) %> ago by <%= link_to comment.user.username, comment.user %> <br> <%= pluralize(comment.likes.count, "Like") %> &#160; <%= pluralize(comment.dislikes.count, "Dislike") %>  
<br>  
  <% else %>
  <span class="content"><% if comment.user == @content.user %><b style="color:blue;"><i>This comment is hidden due to too many dislikes.</i></b> <% else %> <b style="color:darkblue;"><i>This comment is hidden due to too many dislikes.</i></b> <% end %></span>
<br>
  <span class="timestamp">
      <%= pluralize(comment.likes.count, "Like") %> &#160; <%= pluralize(comment.dislikes.count, "Dislike") %> &#160;&#160;&#160;&#160;&#160; Posted <%= time_ago_in_words(comment.created_at) %> ago by <%= link_to comment.user.username, comment.user %>
<br>
  <% end %>

  <div class="dropdown">
    <a class="btn-custom3" class="dropdown-toggle" data-toggle="dropdown" href="#">Show</a>
    <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">

      <table class="microposts" summary="User microposts">

<tr>
  <td class="micropost">

          <span class="content"><% if comment.user == @content.user %><b style="color:firebrick;"><%= wrap(comment.body) %></b> <% else %> <b style="color:firebrick;"><%= wrap(comment.body) %></b><% end %></span>
        </br>
        </br>
      <div class="bs-docs-example">
      <ul class="nav nav-pills">
    <% if signed_in? %>
    <li><%= link_to "Like", like_comment_path(comment) %></li>
    <li><%= link_to "Dislike", dislike_comment_path(comment) %></li>
    <% else %>
    <li><%= link_to "Like", signup_path %></li>
    <li><%= link_to "Dislike", signup_path %></li>
    <% end %>
      <% if current_user?(comment.user) %>
     <li><%= link_to "Delete", polymorphic_url([@content, comment]), :class => "btn-customdislike", :method => :delete,
                                       :confirm => "Are you sure you want to delete this comment?" %></li> 
  <% end %>
  <% if signed_in? %>
    <% if current_user.admin? %>
       <li><%= link_to "Admin Delete", polymorphic_url([@content, comment]), :class => "btn-customdislike", :method => :delete, :confirm => "You sure?" %></li>
      <% end %>
      <% end %>
    </ul>
  </div>

        </td>
  </tr>

</table>  

</ul>
</div>
  </span>

  </td>
  </tr>

</table>   

    <% else %>

<table class="microposts" summary="User microposts">

<tr>
  <td class="micropost">

    <% if is_mobile_view? %>
    <span class="content" style="width: 125%;"><% if comment.user == @content.user %><b style="color:blue;"><%= wrap(comment.body) %></b> <% else %> <b><%= wrap(comment.body) %></b><% end %></span>
    <br> 
    <span class="timestamp" style="width: 130%;">
      Posted <%= time_ago_in_words(comment.created_at) %> ago by <%= link_to comment.user.username, comment.user %> <br> <%= pluralize(comment.likes.count, "Like") %> &#160; <%= pluralize(comment.dislikes.count, "Dislike") %> 
    <br>
    <% if signed_in? %>
    &#160; <%= link_to "Like", like_comment_path(comment) %> &#160;&#160;
    <%= link_to "Dislike", dislike_comment_path(comment) %> &#160;&#160;
    <% else %>
    &#160; <%= link_to "Like", signup_path %> &#160;&#160;
    <%= link_to "Dislike", signup_path %> &#160;&#160;
    <% end %>
      <% if current_user?(comment.user) %>
     <%= link_to "Delete", polymorphic_url([@content, comment]), :class => "btn-customdislike", :method => :delete,
                                       :confirm => "Are you sure you want to delete this comment?" %> 
  <% end %>
  <% if signed_in? %>
    <% if current_user.admin? %>
       <%= link_to "Admin Delete", polymorphic_url([@content, comment]), :class => "btn-customdislike", :method => :delete, :confirm => "You sure?" %>
      <% end %>
      <% end %>
    </span>
    <% else %>
    <span class="content"><% if comment.user == @content.user %><b style="color:blue;"><%= wrap(comment.body) %></b> <% else %> <b><%= wrap(comment.body) %></b><% end %></span>
    <br> 
    <span class="timestamp">
      <%= pluralize(comment.likes.count, "Like") %> &#160; <%= pluralize(comment.dislikes.count, "Dislike") %> &#160;&#160;&#160;&#160;&#160; Posted <%= time_ago_in_words(comment.created_at) %> ago by <%= link_to comment.user.username, comment.user %> 
    <br>
    <% if signed_in? %>
    &#160; <%= link_to "Like", like_comment_path(comment) %> &#160;&#160;
    <%= link_to "Dislike", dislike_comment_path(comment) %> &#160;&#160;
    <% else %>
    &#160; <%= link_to "Like", signup_path %> &#160;&#160;
    <%= link_to "Dislike", signup_path %> &#160;&#160;
    <% end %>
      <% if current_user?(comment.user) %>
     <%= link_to "Delete", polymorphic_url([@content, comment]), :class => "btn-customdislike", :method => :delete,
                                       :confirm => "Are you sure you want to delete this comment?" %> 
  <% end %>
  <% if signed_in? %> &#160;&#160;&#160;&#160;
      <% if current_user.admin? %>
       <%= link_to "Admin Delete", polymorphic_url([@content, comment]), :class => "btn-customdislike", :method => :delete, :confirm => "You sure?" %>
      <% end %>
      <% end %>
    </span>
  <% end %>
  </td>


  </tr>

</table>   

<% end %>

<% end %>

app/views/contents/_content.html.erb
<% @everything.sort_by(&:created_at).reverse.each do |content| %>

<% if content.instance_of?(Content) %>

<tr>
  <td class="micropost">
    <span class="content"><b><%= wrap(content.content.to_s) %></b></span>
    </br> 
    </br>
    <span class="timestamp">
      Posted <%= time_ago_in_words(content.created_at) %> ago by <%= link_to content.user.username, content.user %>
    </span>

    <ul class="nav nav-pills">
      <li><%= link_to "Link to Page", content %></li>
      <li><%= link_to pluralize(content.comments.count, "Comment"), content_comments_path(content.id), :class => "ajax" %>
<script>
    jQuery('a.ajax').colorbox();
</script></li>
<li><%= link_to "Reply", reply_content_comments_path(content.id), :class => "ajax" %>
<script>
    jQuery('a.ajax').colorbox();
</script></li>
     <li><% user = content.user rescue User.find(content.user_id) %>
      <% if current_user?(user) %>
      <%= link_to "Delete", content, :method => :delete,
                                       :confirm => "Are you sure you want to delete this post?" %>
      <% end %></li>
</ul>
 
</td>
</tr>

<% elsif content.instance_of?(Photo) %>

<tr>
  <td class="micropost">
    <% if content.captions.any? %>
    <% content.captions.each do |caption| %>
    <span class="content"><b><%= wrap(caption.body) %></b></span>
    <% end %>
    </br>
    </br>
    <% end %>
    <span class="content"><%= image_tag content.image_url.to_s if content.image? %></span>
    </br> 
    </br>
    <span class="timestamp">
      Posted <%= time_ago_in_words(content.created_at) %> ago by <%= link_to content.user.username, content.user %>
    </span>

    <ul class="nav nav-pills">
      <li><%= link_to "Link to Page", content %></li>
      <li><%= link_to pluralize(content.comments.count, "Comment"), content_comments_path(content.id), :class => "ajax" %>
<script>
    jQuery('a.ajax').colorbox();
</script></li>
<li><%= link_to "Reply", reply_content_comments_path(content.id), :class => "ajax" %>
<script>
    jQuery('a.ajax').colorbox();
</script></li>
     <li><% user = content.user rescue User.find(content.user_id) %>
      <% if current_user?(user) %>
      <%= link_to "Delete", content, :method => :delete,
                                       :confirm => "Are you sure you want to delete this post?" %>
      <% end %></li>
</ul>

</td>
</tr>

<% end %>
<% end %>

app/views/contents/create.html.erb
<h1>Contents#create</h1>
<p>Find me in app/views/contents/create.html.erb</p>

app/views/contents/destroy.html.erb
<h1>Contents#destroy</h1>
<p>Find me in app/views/contents/destroy.html.erb</p>

app/views/contents/dislike.html.erb
<h1>Contents#dislike</h1>
<p>Find me in app/views/contents/dislike.html.erb</p>

app/views/contents/index.html.erb
<%= form_tag contents_path, :method => 'get' do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil %>
  </p>
<% end %>


app/views/contents/like.html.erb
<h1>Contents#like</h1>
<p>Find me in app/views/contents/like.html.erb</p>

app/views/contents/new.html.erb
<%= simple_form_for(setup_content(current_user.contents.build(params[:content]))) do |f| %>
  <%= f.input :image, :as => :file, label: false %>
  <%= f.input :remote_image_url, label: "or enter image URL", placeholder: 'Enter URL' %>
  <%= f.simple_fields_for :captions do |b| %>
  	<%= b.input :body, :as => :text, label: 'Write a caption', placeholder: 'Enter a caption =D' %>
  <% end %>
  <%= f.submit "Submit Image", :class => 'btn btn-primary' %>
<% end %>

app/views/contents/show.html.erb
<% if is_mobile_view? %>
  <table class="profile" summary="For signed-in users">
    <tr>
      <td class="main">
  <% else %>
  <table class="shadowborder">
    <tr>
      <td class="test">
  <% end %>

<% if is_mobile_view? %>
<h4><span style="color:orangered; font-size: 150%;">Stumweb</span><span style="color:mediumblue; font-size: 115%;">: the front page of New York City!</span></h4>

<br>
<% else %>
<h3 style="margin-left: 15px; width: 500px;"><span class="textshadow1" style="color:orangered; font-size: 120%;">Stumweb</span><span class="textshadow2" style="color:mediumblue; font-size: 95%;">: the front page of New York City!</span></h3>
<% end %>
      
      <% if is_mobile_view? %>
      <table class="microposts" summary="User microposts">
      <% else %>
      <table class="microposts" summary="User microposts" style="margin-left: 15px; width: 500px">
      <% end %>  

<tr>
  <td class="micropost" style="border: 2px solid; border-left:none; border-right:none;">
    <span class="content"><b><%= wrap(@content.content) %></b></span>
    <br> 
    <br>

    <iframe src="http://www.facebook.com/plugins/like.php?app_id=212715052108961&amp;href=PAGEURL;send=false&amp;layout=button_count&amp;width=50&amp;show_faces=false&amp;action=like&amp;colorscheme=light&amp;font&amp;height=21" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:50px; height:21px;" allowTransparency="true"></iframe>
    <a href="https://twitter.com/share" class="twitter-share-button" data-dnt="true" data-count="none" data-via="twitterapi">Tweet</a>
    <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="https://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>

    <% if is_mobile_view? %>
    <span class="timestamp" style="width: 125%;">
          Posted <%= time_ago_in_words(@content.created_at) %> ago by <%= link_to @content.user.username, @content.user %> <br>
      <%= pluralize(@content.likes.count, "Like") %> &#160; <%= pluralize(@content.dislikes.count, "Dislike") %> &#160; <%= pluralize(@content.impressionist_count, "Views") %>
      &#160;
  </span>
    <% else %>
    <span class="timestamp">
      <%= pluralize(@content.likes.count, "Like") %> &#160; <%= pluralize(@content.dislikes.count, "Dislike") %> &#160;&#160;&#160;&#160;&#160; Posted <%= time_ago_in_words(@content.created_at) %> ago by <%= link_to @content.user.username, @content.user %> &#160;&#160;&#160;&#160;&#160; <%= pluralize(@content.impressionist_count, "Views") %>
    </span>
  <% end %>

      <% content = Content.find(params[:id]) %>
      <% if signed_in? %>
      &#160; <%= link_to "Viral", like_content_path(content), :class => "btn-customlike" %> &#160; 
      <%= link_to "Lame", dislike_content_path(content), :class => "btn-customdislike" %>
      <% else %>
      &#160; <%= link_to "Viral", signup_path, :class => "btn-customlike" %> &#160; 
      <%= link_to "Lame", signup_path, :class => "btn-customdislike" %>
      <% end %>
      &#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;
      <% user = @content.user rescue User.find(@content.user_id) %>
      <% if current_user?(user) %>
      <%= link_to "Delete", @content, :class => "btn-customdislike", :method => :delete,
                                       :confirm => "Are you sure you want to delete this post?",
                                       :title => @content.content %>   
  <% end %> &#160;&#160;&#160;&#160;&#160;    
  <% if signed_in? %>
      <% if current_user.admin? %>
       <%= link_to "Admin Delete", @content, :class => "btn-customdislike", :method => :delete, :confirm => "You sure?" %>
      <% end %>
    <% end %>
</td>
</br>
</br>

    <table class="profile" summary="Profile information">
  <tr>
    <td class="main">
      

    <% if is_mobile_view? %>
    <div style="margin-left: -20px;">
    <% else %>
    <div>   
    <% end %>
        <% if @content.comments.any? %>
        <h5 style="color:blue;">Top Comments</h5>
  <% @topcomments.each do |comment| %>

    <% if (comment.dislikes.count - comment.likes.count) > 2 %>

    <table class="microposts" summary="User microposts">

<tr>
  <td class="micropost">

  <% if is_mobile_view? %>
  <span class="content" style="width: 125%;"><% if comment.user == @content.user %><b style="color:blue;"><i>This comment is hidden due to too many dislikes.</i></b> <% else %> <b style="color:darkblue;"><i>This comment is hidden due to too many dislikes.</i></b> <% end %></span>
<br>
  <span class="timestamp" style="width: 130%;">
      Posted <%= time_ago_in_words(comment.created_at) %> ago by <%= link_to comment.user.username, comment.user %> <br> <%= pluralize(comment.likes.count, "Like") %> &#160; <%= pluralize(comment.dislikes.count, "Dislike") %>  
<br>  
  <% else %>
  <span class="content"><% if comment.user == @content.user %><b style="color:blue;"><i>This comment is hidden due to too many dislikes.</i></b> <% else %> <b style="color:darkblue;"><i>This comment is hidden due to too many dislikes.</i></b> <% end %></span>
<br>
  <span class="timestamp">
      <%= pluralize(comment.likes.count, "Like") %> &#160; <%= pluralize(comment.dislikes.count, "Dislike") %> &#160;&#160;&#160;&#160;&#160; Posted <%= time_ago_in_words(comment.created_at) %> ago by <%= link_to comment.user.username, comment.user %>
<br>
  <% end %>

  <div class="dropdown">
    <a class="btn-custom3" class="dropdown-toggle" data-toggle="dropdown" href="#">Show</a>
    <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">

      <table class="microposts" summary="User microposts">

<tr>
  <td class="micropost">

          <span class="content"><% if comment.user == @content.user %><b style="color:firebrick;"><%= wrap(comment.body) %></b> <% else %> <b style="color:firebrick;"><%= wrap(comment.body) %></b><% end %></span>
        </br>
        </br>
      <div class="bs-docs-example">
      <ul class="nav nav-pills">
    <% if signed_in? %>
    <li><%= link_to "Like", like_comment_path(comment) %></li>
    <li><%= link_to "Dislike", dislike_comment_path(comment) %></li>
    <% else %>
    <li><%= link_to "Like", signup_path %></li>
    <li><%= link_to "Dislike", signup_path %></li>
    <% end %>
      <% if current_user?(comment.user) %>
     <li><%= link_to "Delete", polymorphic_url([@content, comment]), :class => "btn-customdislike", :method => :delete,
                                       :confirm => "Are you sure you want to delete this comment?" %></li> 
  <% end %>
  <% if signed_in? %>
    <% if current_user.admin? %>
       <li><%= link_to "Admin Delete", polymorphic_url([@content, comment]), :class => "btn-customdislike", :method => :delete, :confirm => "You sure?" %></li>
      <% end %>
      <% end %>
    </ul>
  </div>

        </td>
  </tr>

</table>  

</ul>
</div>
  </span>

  </td>
  </tr>

</table>   

    <% else %>

<table class="microposts" summary="User microposts">

<tr>
  <td class="micropost">

    <% if is_mobile_view? %>
    <span class="content" style="width: 125%;"><% if comment.user == @content.user %><b style="color:blue;"><%= wrap(comment.body) %></b> <% else %> <b><%= wrap(comment.body) %></b><% end %></span>
    <br> 
    <span class="timestamp" style="width: 130%;">
      Posted <%= time_ago_in_words(comment.created_at) %> ago by <%= link_to comment.user.username, comment.user %> <br> <%= pluralize(comment.likes.count, "Like") %> &#160; <%= pluralize(comment.dislikes.count, "Dislike") %> 
    <br>
    <% if signed_in? %>
    &#160; <%= link_to "Like", like_comment_path(comment) %> &#160;&#160;
    <%= link_to "Dislike", dislike_comment_path(comment) %> &#160;&#160;
    <% else %>
    &#160; <%= link_to "Like", signup_path %> &#160;&#160;
    <%= link_to "Dislike", signup_path %> &#160;&#160;
    <% end %>
      <% if current_user?(comment.user) %>
     <%= link_to "Delete", polymorphic_url([@content, comment]), :class => "btn-customdislike", :method => :delete,
                                       :confirm => "Are you sure you want to delete this comment?" %> 
  <% end %>
  <% if signed_in? %>
    <% if current_user.admin? %>
       <%= link_to "Admin Delete", polymorphic_url([@content, comment]), :class => "btn-customdislike", :method => :delete, :confirm => "You sure?" %>
      <% end %>
      <% end %>
    </span>
    <% else %>
    <span class="content"><% if comment.user == @content.user %><b style="color:blue;"><%= wrap(comment.body) %></b> <% else %> <b><%= wrap(comment.body) %></b><% end %></span>
    <br> 
    <span class="timestamp">
      <%= pluralize(comment.likes.count, "Like") %> &#160; <%= pluralize(comment.dislikes.count, "Dislike") %> &#160;&#160;&#160;&#160;&#160; Posted <%= time_ago_in_words(comment.created_at) %> ago by <%= link_to comment.user.username, comment.user %> 
    <br>
    <% if signed_in? %>
    &#160; <%= link_to "Like", like_comment_path(comment) %> &#160;&#160;
    <%= link_to "Dislike", dislike_comment_path(comment) %> &#160;&#160;
    <% else %>
    &#160; <%= link_to "Like", signup_path %> &#160;&#160;
    <%= link_to "Dislike", signup_path %> &#160;&#160;
    <% end %>
      <% if current_user?(comment.user) %>
     <%= link_to "Delete", polymorphic_url([@content, comment]), :class => "btn-customdislike", :method => :delete,
                                       :confirm => "Are you sure you want to delete this comment?" %> 
  <% end %>
  <% if signed_in? %>
    <% if current_user.admin? %>
       <%= link_to "Admin Delete", polymorphic_url([@content, comment]), :class => "btn-customdislike", :method => :delete, :confirm => "You sure?" %>
      <% end %>
      <% end %>
    </span>
    <% end %>
  </td>


  </tr>

</table>   

<% end %>

<% end %>
<br>

<%# the nav-tabs border is commented out in line 3016 in the application.css file %>
      <ul class="nav nav-tabs">
<% if signed_in? %>
      <li>
        <%= form_for [@content, current_user.comments.new] do |f| %>
      <%= render 'shared/error_messages', :object => f.object %>
    <div class="field">
      <% if is_mobile_view? %>
    <%= f.text_area :body, :style => "width: 105%", :placeholder => "Reply" %>
      <% else %>
    <%= f.text_area :body, :style => "width: 475px", :placeholder => "Reply" %>
      <% end %>
    </div>
    <div class="actions">
    <%= f.submit "Submit", :class => 'btn btn-success' %>
    </div>
    <% end %>
  </li>
  <% else %>
  <li><%= link_to "Reply", signup_path, :class => "btn-custom3" %></li>
<% end %>
</ul>

<h5 style="color:blue;">All Comments</h5>
<% if is_mobile_view? %>
<div id="pages">
          <%= render 'comments' %>
</div>
        <%= will_paginate @comments, :page_links => false %>
<% else %>
<div id="pages">
          <%= render 'comments' %>
</div>
        <%= will_paginate @comments, :page_links => false %>
<% end %>
      <% end %>

</div>
          </td>
      </tr>
</table>

<%# the nav-tabs border is commented out in line 3016 in the application.css file %>
      <ul class="nav nav-tabs">
<% if signed_in? %>
      <li>
     <div class="dropdown">
    <a class="btn-custom3" class="dropdown-toggle" data-toggle="dropdown" href="#">Reply</a>
    <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
        <%= form_for [@content, current_user.comments.new] do |f| %>
      <%= render 'shared/error_messages', :object => f.object %>
    <div class="field">
    <%= f.text_area :body %>
    </div>
    <div class="actions">
    <%= f.submit "Submit", :class => 'btn btn-success' %>
    </div>
    <% end %>
    </ul>
    </div>
  </li>
    <% else %>
  <li><%= link_to "Reply", signup_path, :class => "btn-custom3", :style => "margin-left: 15px" %></li>
<% end %>
</ul>

  </td>
    <% if is_mobile_view? %>
      <% else %>

    <% if signed_in? %>
      <td class="sidebar2 round">
        <%= render 'shared/user_info' %>
      </td>

    <% else %>
      <td class="sidebar2 round">
        <%= render 'shared/user_info_signedout' %>
      </td>
    <% end %>

  <% end %>
</tr>
</table>

    </td>
    
  </tr>
</table>

app/views/contents/show.js.erb
$('#pages').append('<%= j render('comments') %>');
<% if @comments.next_page %>
  $('.pagination').replaceWith('<%= j will_paginate(@comments) %>');
<% else %>
  $('.pagination').remove();
<% end %>
<% sleep 1 %>