config/routes.rb
Newstumweb::Application.routes.draw do

  resources :teams do
    resources :users
  end

  resources :users do
    get "new_message", :on => :collection
    post "create_message", :on => :collection
    delete "destroy_message", :on => :collection

    member do
      get 'likes'
      get 'dislikes'
      get 'messages'
      get 'inbox'
      get 'outbox'
      get 'show_message'
    end
  end

  resources :users do
    resources :comments
      end
  resources :sessions, :only => [:new, :create, :destroy]
  resources :photos do
    member do
      get 'like'
      get 'dislike'
    end
  end

  resources :password_resets

  resources :photos do
    resources :comments do
     get 'reply', :on => :collection
   end
 end

  resources :contents do
    member do
      get 'like'
      get 'dislike'
    end
  end

  resources :contents do
    resources :comments do
     get 'reply', :on => :collection
   end
 end

 resources :comments do
  member do
    get 'like'
    get 'dislike'
  end
end

  resources :photos do
    resources :captions 
  end

  root :to => "pages#home"

  match '/contact', :to => 'pages#contact'
  match '/about', :to => 'pages#about'
  match '/help', :to => 'pages#help'
  match '/contest', :to => 'pages#contest'
  match '/bestfeatures', :to => 'pages#bestfeatures'
  match '/index', :to => 'users#index'
  match '/signup', :to => 'users#new'
  match '/signin', :to => 'sessions#new'
  match '/sessions', :to => 'sessions#create'
  match '/signout', :to => 'sessions#destroy'
  match '/comments', :to => 'comments#create'
  match '/contents', :to => 'contents#index'
  match '/contents/:id', :to => 'contents#show'
  match '/contents/:content_id/comments', :to => 'comments#index'
  match '/photos/:photo_id/comments', :to => 'comments#index'
  match '/contents/:content_id/comments/reply', :to => 'comments#reply'
  match '/results', :to => 'contents#index'
  match '/newteam', :to => 'teams#new'
  match '/jointeam', :to => 'teams#join'

end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_voter
  acts_as_messageable :table_name => "table_name",
                      :required   => :body,              
                      :dependent  => :destroy             
  
  attr_accessor :password
  attr_accessible :username, :email, :password, :password_confirmation, :score #, :team_id
  
  belongs_to :team
  has_many :contents, :dependent => :destroy
  has_many :photos, :dependent => :destroy
  has_many :comments, :dependent => :destroy  # as: :commentable, 
  #has_many :relationships, :dependent => :destroy,
  # :foreign_key => "follower_id"
  #has_many :reverse_relationships, :dependent => :destroy,
  # :foreign_key => "followed_id",
  # :class_name => "Relationship"
  #has_many :following, :through => :relationships, :source => :followed
  #has_many :followers, :through => :reverse_relationships,
  # :source => :follower

  #include PgSearch
  #multisearchable :against => [:username, :email]
  
  email_regex = /(\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})(,\s*([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,}))*\z)/i
  
  validates :username, :presence => true,
                       :length => { :maximum => 50 },
                       :uniqueness => { :case_sensitive => false }
  validates :email,    :format => { :with => email_regex },
                       :allow_blank => true,
                       :uniqueness => { :case_sensitive => false }
  validates :password, :presence => true, on: :create,
                       :confirmation => true, on: :create,
                       :length => { :within => 6..40 }, on: :create
  validates :password, :presence => true, on: :update,
                       :confirmation => true, on: :update,
                       :length => { :within => 6..40 }, on: :update

  before_save :encrypt_password
  
  def has_password?(submitted_password)
    encrypted_password == encrypt(submitted_password)
  end

  def send_password_reset
    token = SecureRandom.urlsafe_base64
    if self.password_reset_token == token
      newtoken = SecureRandom.urlsafe_base64
      self.update_column(:password_reset_token, newtoken)
    else
      self.update_column(:password_reset_token, token)
    end
    self.update_column(:password_reset_sent_at, Time.zone.now)
    #save!(:validate => false)
    UserMailer.password_reset(self).deliver
  end

  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while User.exists?(column => self[column])
  end
  
  class << self
    def authenticate(username, submitted_password)
      user = find_by_username(username)
      (user && user.has_password?(submitted_password)) ? user : nil
    end
    
    def authenticate_with_salt(id, cookie_salt)
      user = find_by_id(id)
      (user && user.salt == cookie_salt) ? user : nil
    end
  end

  private
  
    def encrypt_password
      self.salt = make_salt unless has_password?(password)
      self.encrypted_password = encrypt(password)
    end
  
    def encrypt(string)
      secure_hash("#{salt}--#{string}")
    end
    
    def make_salt
      secure_hash("#{Time.now.utc}--#{password}")
    end
    
    def secure_hash(string)
      Digest::SHA2.hexdigest(string)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate,
                :only => [:edit, :update, :destroy]
  before_filter :correct_user, :only => [:edit, :update]
  before_filter :admin_user, :only => :destroy
  
  def index
    @users = User.paginate(:page => params[:page])
    @title = "All users"
  end
  
  def show
    @user = User.find(params[:id])
    @contents = @user.contents #.paginate(:page => params[:page])
    @photos = @user.photos #.paginate(:page => params[:page])
    @everything = (@contents + @photos).sort_by(&:content_changed_at).reverse.paginate(page: params[:page], :per_page => 5)
    @title = @user.username
  end

  def likes
    @user = User.find(params[:id])
    @likes = @user.find_liked_items.reverse.paginate(page: params[:page], :per_page => 5)
  end

  def dislikes
    @user = User.find(params[:id])
    @dislikes = @user.find_disliked_items.reverse.paginate(page: params[:page], :per_page => 5)
  end

  def new
    @user = User.new
    @title = "Sign up"
  end
  
  def create
    @user = User.new(params[:user])
    if @user.save
      sign_in @user
      redirect_to @user, :flash => { :success => "Welcome to the Sample App!" }
    else
      @title = "Sign up"
      render 'new' 
    end
  end

  def new_message
    @message = ActsAsMessageable::Message.new
  end

  def create_message
    @to = User.find_by_username(params[:message][:to])
    current_user.send_message(@to, params[:message][:body])
    redirect_to @user
  end
  
  def destroy_message
    @message = current_user.messages.find(params[:id])
    @message.destroy
    redirect_to inbox_user_path(current_user)
  end

  def messages
    @messages = current_user.messages
  end

  def inbox
    @messages = current_user.received_messages.sort_by(&:created_at).reverse.paginate(page: params[:page], :per_page => 5)
  end

  def outbox
    @messages = current_user.sent_messages
  end


  def show_message
    @message = current_user.messages.find(params[:id])
  end

  def edit
    @title = "Edit user"
  end
  
  def update
    @user = current_user
    if @user.update_attributes(params[:user])
      sign_in @user
      redirect_to @user, :flash => { :success => "Profile updated." }
    else
      @title = "Edit user"
      render 'edit'
    end
  end

  def destroy
    @user.destroy
    redirect_to root_path, :flash => { :success => "User destroyed." }
  end

  private

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_path) unless current_user?(@user)
    end
    
    def admin_user
      redirect_to root_path unless current_user.admin?
    end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = { :size => 50 })
    gravatar_image_tag(user.email.downcase, :alt => h(user.username),
                                            :class => 'gravatar',
                                            :gravatar => options)
  end
end

app/views/users/_dislikesfeed.html.erb
<% @dislikes.each do |content| %>

<% if content.instance_of?(Content) %>

<table class="microposts" summary="User microposts" style="width: 500px">

<tr>
  <td class="micropost">
    <span class="content"><b><%= raw(truncate(wrap(content.content.to_s), :length => 421, :separator => ' ', :omission => (link_to "... (more)", content))) %></b></span>
    </br> 
    </br>
    <span class="timestamp">
      <%= pluralize(content.likes.count, "Like") %> &#160; <%= pluralize(content.dislikes.count, "Dislike") %> &#160;&#160;&#160;&#160;&#160; Posted <%= time_ago_in_words(content.created_at) %> ago by <%= link_to content.user.username, content.user %> &#160;&#160;&#160;&#160;&#160; <%= pluralize(content.impressionist_count, "Views") %>
    </span>

            <div class="bs-docs-example">
            <ul class="nav nav-pills">
              <% if signed_in? %>
                <li><%= link_to "Viral", like_content_path(content), :class => "btn-customlike" %></li>
                <li><%= link_to "Lame", dislike_content_path(content), :class => "btn-customdislike" %></li>
              <% else %>
              <li><%= link_to "Viral", signup_path, :class => "btn-customlike" %></li>
              <li><%= link_to "Lame", signup_path, :class => "btn-customdislike" %></li> 
              <% end %> 
              <li><%= link_to "Show Post", content, :class => "btn-custom3" %></li>
              <li><%= link_to pluralize(content.comments.count, "Comment"), content, :class => "btn-custom3" %></li>
                <% if signed_in? %>
              <li class="dropdown">
                <a class="btn-custom3" class="dropdown-toggle" id="drop4" role="button" data-toggle="dropdown" href="#">Reply</a>
                <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
                  <%= form_for [content, current_user.comments.new] do |f| %>
                    <%= render 'shared/error_messages', :object => f.object %>
                      <div class="field">
                      <%= f.text_area :body %>
                      </div>
                      <div class="actions">
                      <%= f.submit "Submit" %>
                      </div>
                    <% end %>
                </ul>
              </li>
                <% else %>
                  <li><%= link_to "Reply", signin_path, :class => "btn-custom3" %></li>
                <% end %>
              <li><% user = content.user rescue User.find(content.user_id) %>
                <% if current_user?(user) %>
                <%= link_to "Delete", content, :class => "btn-customdislike", :method => :delete,
                                                 :confirm => "Are you sure you want to delete this post?" %>
                <% end %></li>
            </ul> <!-- /tabs -->
          </div> 
 
</td>
</tr>

</table>

<% elsif content.instance_of?(Photo) %>

<table class="microposts" summary="User microposts">

<tr>
  <td class="micropost">
    <% if content.captions.any? %>
    <% content.captions.each do |caption| %>
    <span class="content"><b><%= raw(truncate(wrap(caption.body), :length => 421, :separator => ' ', :omission => (link_to "... (more)", content))) %></b></span>
    <% end %>
    </br>
    </br>
    <% end %>
    <span class="content"><%= cl_image_tag(content.image_url.to_s, :width => 500, :height => 150, :crop => :fill) if content.image? %></span>
    </br> 
    </br>
    <span class="timestamp">
      <%= pluralize(content.likes.count, "Like") %> &#160; <%= pluralize(content.dislikes.count, "Dislike") %> &#160;&#160;&#160;&#160;&#160; Posted <%= time_ago_in_words(content.created_at) %> ago by <%= link_to content.user.username, content.user %> &#160;&#160;&#160;&#160;&#160; <%= pluralize(content.impressionist_count, "Views") %>
    </span>

            <div class="bs-docs-example">
            <ul class="nav nav-pills">
              <% if signed_in? %>
                <li><%= link_to "Viral", like_content_path(content), :class => "btn-customlike" %></li>
                <li><%= link_to "Lame", dislike_content_path(content), :class => "btn-customdislike" %></li> 
              <% else %>
              <li><%= link_to "Viral", signup_path, :class => "btn-customlike" %></li>
              <li><%= link_to "Lame", signup_path, :class => "btn-customdislike" %></li> 
              <% end %>
              <li><%= link_to "Show Post", content, :class => "btn-custom3" %></li>
              <li><%= link_to pluralize(content.comments.count, "Comment"), content, :class => "btn-custom3" %></li>
                <% if signed_in? %>
              <li class="dropdown">
                <a class="btn-custom3" class="dropdown-toggle" id="drop4" role="button" data-toggle="dropdown" href="#">Reply</a>
                <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
                  <%= form_for [content, current_user.comments.new] do |f| %>
                    <%= render 'shared/error_messages', :object => f.object %>
                      <div class="field">
                      <%= f.text_area :body %>
                      </div>
                      <div class="actions">
                      <%= f.submit "Submit" %>
                      </div>
                    <% end %>
                </ul>
              </li>
                <% else %>
                  <li><%= link_to "Reply", signin_path, :class => "btn-custom3" %></li>
                <% end %>
              <li><% user = content.user rescue User.find(content.user_id) %>
                <% if current_user?(user) %>
                <%= link_to "Delete", content, :class => "btn-customdislike", :method => :delete,
                                                 :confirm => "Are you sure you want to delete this post?" %>
                <% end %></li>
            </ul> <!-- /tabs -->
          </div> 


</td>
</tr>

</table>

<% end %>
<% end %>

app/views/users/_fields.html.erb
<div class="field">
  <%= f.label :username %><br />
  <%= f.text_field :username %>
</div>
<div class="field">
  <%= f.label :email, "Email (optional)" %><br />
  <%= f.text_field :email %>
</div>
<div class="field">
  <%= f.label :password %><br />
  <%= f.password_field :password %>
</div>
<div class="field">
  <%= f.label :password_confirmation, "Confirmation" %><br />
  <%= f.password_field :password_confirmation %>
</div>

app/views/users/_user.html.erb
<li>
  <%= link_to user.username, user %> </br>
  Content Count: <%= user.contents.count + user.photos.count %>
  <br>
  Score Count: <%= user.score %>
 </li>

app/views/users/_userfeed.html.erb
<% @everything.each do |content| %>

<% if content.instance_of?(Content) %>

<table class="microposts" summary="User microposts" style="width: 500px">

<tr>
  <td class="micropost">
    <span class="content"><b><%= raw(truncate(wrap(content.content.to_s), :length => 421, :separator => ' ', :omission => (link_to "... (more)", content))) %></b></span>
    <br> 
    <br>
    <% if is_mobile_view? %>
    <span class="timestamp" style="width: 125%;">
      Posted <%= time_ago_in_words(content.created_at) %> ago by <%= link_to content.user.username, content.user %> <br> <%= pluralize(content.likes.count, "Like") %> &#160; <%= pluralize(content.dislikes.count, "Dislike") %> 
      &#160; 
      <% user = content.user rescue User.find(content.user_id) %>
          <% if current_user?(user) %>
          <%= link_to "Delete", content, :class => "btn-customdislike", :method => :delete, 
                                           :confirm => "Are you sure you want to delete this post?" %>
          <% end %>
      &#160; 
      <% if signed_in? %>
        <% if current_user.admin? %>
          <%= link_to "Admin Delete", content, :class => "btn-customdislike", :method => :delete, :confirm => "You sure?" %>
        <% end %> 
      <% end %>
    </span>
    <% else %>
    <span class="timestamp">
      <%= pluralize(content.likes.count, "Like") %> &#160; <%= pluralize(content.dislikes.count, "Dislike") %> &#160;&#160;&#160;&#160;&#160; Posted <%= time_ago_in_words(content.created_at) %> ago by <%= link_to content.user.username, content.user %> &#160;&#160;&#160;&#160;&#160; <%= pluralize(content.impressionist_count, "Views") %>
    </span>
    <% end %>

                <% if is_mobile_view? %>
        <div class="bs-docs-example" style="font-size: 60%; width: 125%;">
            <ul class="nav nav-pills">
              <% if signed_in? %>
                <li><%= link_to "Viral", like_content_path(content), :class => "btn-customlike" %></li>
                <li><%= link_to "Lame", dislike_content_path(content), :class => "btn-customdislike" %></li> 
              <% else %>
              <li><%= link_to "Viral", signup_path, :class => "btn-customlike" %></li>
              <li><%= link_to "Lame", signup_path, :class => "btn-customdislike" %></li> 
              <% end %>
                <% if signed_in? %>
              <li class="dropdown">
                <a class="btn-custom3" class="dropdown-toggle" id="drop4" role="button" data-toggle="dropdown" href="#">Reply</a>
                <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
                  <%= form_for [content, current_user.comments.new] do |f| %>
                    <%= render 'shared/error_messages', :object => f.object %>
                      <div class="field">
                      <%= f.text_area :body %>
                      </div>
                      <div class="actions">
                      <%= f.submit "Submit", :class => "btn btn-success" %>
                      </div>
                    <% end %>
                </ul>
              </li>
                <% else %>
                  <li><%= link_to "Reply", signup_path, :class => "btn-custom3" %></li>
                <% end %>
                <li><%= link_to "Show Post", content, :class => "btn-custom3" %></li>
                <li><%= link_to pluralize(content.comments.count, "Comment"), content, :class => "btn-custom3" %></li>
              </ul> <!-- /tabs -->
          </div>
          <% else %>
                  <div class="bs-docs-example">
            <ul class="nav nav-pills">
              <% if signed_in? %>
                <li><%= link_to "Viral", like_content_path(content), :class => "btn-customlike" %></li>
                <li><%= link_to "Lame", dislike_content_path(content), :class => "btn-customdislike" %></li> 
              <% else %>
              <li><%= link_to "Viral", signup_path, :class => "btn-customlike" %></li>
              <li><%= link_to "Lame", signup_path, :class => "btn-customdislike" %></li> 
              <% end %>
              <li><%= link_to "Show Post", content, :class => "btn-custom3" %></li>
              <li><%= link_to pluralize(content.comments.count, "Comment"), content, :class => "btn-custom3" %></li>
                <% if signed_in? %>
              <li class="dropdown">
                <a class="btn-custom3" class="dropdown-toggle" id="drop4" role="button" data-toggle="dropdown" href="#">Reply</a>
                <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
                  <%= form_for [content, current_user.comments.new] do |f| %>
                    <%= render 'shared/error_messages', :object => f.object %>
                      <div class="field">
                      <%= f.text_area :body %>
                      </div>
                      <div class="actions">
                      <%= f.submit "Submit", :class => "btn btn-success" %>
                      </div>
                    <% end %>
                </ul>
              </li>
                <% else %>
                  <li><%= link_to "Reply", signup_path, :class => "btn-custom3" %></li>
                <% end %>
              <li><% user = content.user rescue User.find(content.user_id) %>
                <% if current_user?(user) %>
                <%= link_to "Delete", content, :class => "btn-customdislike", :method => :delete, 
                                                 :confirm => "Are you sure you want to delete this post?" %>
                <% end %></li>
                <% if signed_in? %>
               <li><% if current_user.admin? %>
                     <%= link_to "Admin Delete", content, :class => "btn-customdislike", :method => :delete, :confirm => "You sure?" %>
                    <% end %> </li>
                    <% end %>
              </ul> <!-- /tabs -->
          </div>
          <% end %>  
 
</td>
</tr>

</table>

<% elsif content.instance_of?(Photo) %>

<table class="microposts" summary="User microposts">

<tr>
  <td class="micropost">
    <% if content.captions.any? %>
    <% content.captions.each do |caption| %>
    <span class="content"><b><%= raw(truncate(wrap(caption.body), :length => 421, :separator => ' ', :omission => (link_to "... (more)", content))) %></b></span>
    <% end %>
    <br>
    <br>
    <% end %>
    <span class="content"><%= cl_image_tag(content.image_url.to_s, :width => 500, :height => 150, :crop => :fill) if content.image? %></span>
    <br> 
    <br>
    <% if is_mobile_view? %>
    <span class="timestamp" style="width: 125%;">
      Posted <%= time_ago_in_words(content.created_at) %> ago by <%= link_to content.user.username, content.user %> <br> <%= pluralize(content.likes.count, "Like") %> &#160; <%= pluralize(content.dislikes.count, "Dislike") %>
      &#160; 
      <% user = content.user rescue User.find(content.user_id) %>
          <% if current_user?(user) %>
          <%= link_to "Delete", content, :class => "btn-customdislike", :method => :delete, 
                                           :confirm => "Are you sure you want to delete this post?" %>
          <% end %>
      &#160; 
      <% if signed_in? %>
        <% if current_user.admin? %>
          <%= link_to "Admin Delete", content, :class => "btn-customdislike", :method => :delete, :confirm => "You sure?" %>
        <% end %> 
      <% end %> 
    </span>
    <% else %>
    <span class="timestamp">
      <%= pluralize(content.likes.count, "Like") %> &#160; <%= pluralize(content.dislikes.count, "Dislike") %> &#160;&#160;&#160;&#160;&#160; Posted <%= time_ago_in_words(content.created_at) %> ago by <%= link_to content.user.username, content.user %> &#160;&#160;&#160;&#160;&#160; <%= pluralize(content.impressionist_count, "Views") %>
    </span>
    <% end %>

            <% if is_mobile_view? %>
            <div class="bs-docs-example" style="font-size: 60%; width: 125%;">
            <ul class="nav nav-pills">
              <% if signed_in? %>
                <li><%= link_to "Viral", like_photo_path(content), :class => "btn-customlike" %></li>
                <li><%= link_to "Lame", dislike_photo_path(content), :class => "btn-customdislike" %></li> 
                <% else %>
              <li><%= link_to "Viral", signup_path, :class => "btn-customlike" %></li>
              <li><%= link_to "Lame", signup_path, :class => "btn-customdislike" %></li> 
              <% end %>
                <% if signed_in? %>
              <li class="dropdown">
                <a class="btn-custom3" class="dropdown-toggle" id="drop4" role="button" data-toggle="dropdown" href="#">Reply</a>
                <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
                  <%= form_for [content, current_user.comments.new] do |f| %>
                    <%= render 'shared/error_messages', :object => f.object %>
                      <div class="field">
                      <%= f.text_area :body %>
                      </div>
                      <div class="actions">
                      <%= f.submit "Submit", :class => "btn btn-success" %>
                      </div>
                    <% end %>
                </ul>
              </li>
                <% else %>
                  <li><%= link_to "Reply", signup_path, :class => "btn-custom3" %></li>
                <% end %>    
              <li><%= link_to "Show Post", content, :class => "btn-custom3" %></li>           
              <li><%= link_to pluralize(content.comments.count, "Comment"), content, :class => "btn-custom3" %></li>
            </ul> <!-- /tabs -->
          </div>
          <% else %> 
          <div class="bs-docs-example">
            <ul class="nav nav-pills">
              <% if signed_in? %>
                <li><%= link_to "Viral", like_photo_path(content), :class => "btn-customlike" %></li>
                <li><%= link_to "Lame", dislike_photo_path(content), :class => "btn-customdislike" %></li> 
                <% else %>
              <li><%= link_to "Viral", signup_path, :class => "btn-customlike" %></li>
              <li><%= link_to "Lame", signup_path, :class => "btn-customdislike" %></li> 
              <% end %>
              <li><%= link_to "Show Post", content, :class => "btn-custom3" %></li>
              <li><%= link_to pluralize(content.comments.count, "Comment"), content, :class => "btn-custom3" %></li>
                <% if signed_in? %>
              <li class="dropdown">
                <a class="btn-custom3" class="dropdown-toggle" id="drop4" role="button" data-toggle="dropdown" href="#">Reply</a>
                <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
                  <%= form_for [content, current_user.comments.new] do |f| %>
                    <%= render 'shared/error_messages', :object => f.object %>
                      <div class="field">
                      <%= f.text_area :body %>
                      </div>
                      <div class="actions">
                      <%= f.submit "Submit", :class => "btn btn-success" %>
                      </div>
                    <% end %>
                </ul>
              </li>
                <% else %>
                  <li><%= link_to "Reply", signup_path, :class => "btn-custom3" %></li>
                <% end %>
              <li><% user = content.user rescue User.find(content.user_id) %>
                <% if current_user?(user) %>
                <%= link_to "Delete", content, :class => "btn-customdislike", :method => :delete,
                                                 :confirm => "Are you sure you want to delete this post?" %>
                <% end %></li>
                <% if signed_in? %>
                <li><% if current_user.admin? %>
                     <%= link_to "Admin Delete", content, :class => "btn-customdislike", :method => :delete, :confirm => "You sure?" %>
                    <% end %> </li>
                    <% end %>
            </ul> <!-- /tabs -->
          </div>
          <% end %> 


</td>
</tr>

</table>

<% end %>
<% end %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/destroy_message.html.erb
<h1>Users#destroy_message</h1>
<p>Find me in app/views/users/destroy_message.html.erb</p>

app/views/users/dislikes.html.erb
  <table class="shadowborder">
    <tr>
      <td class="test">
      <% if is_mobile_view? %>
      <h3>
        <span style="color:crimson"><%= @user.username %></span> <span style="color:mediumblue">Dislikes</span>
      </h3>
      <% else %>
      <h3 style="margin-left: 15px;">
        <span style="color:crimson"><%= @user.username %></span> <span style="color:mediumblue">Dislikes</span>
      </h3>
      <% end %>
    <br>

    <% if is_mobile_view? %>
        <% if @dislikes.any? %>
        <div>
          <%= render 'dislikesfeed' %>
        </div>
        <%= will_paginate @dislikes, :page_links => false %>
      <% end %>
    <% else %>
        <% if @dislikes.any? %>
        <div id="pages" style="margin-left: 15px;">
          <%= render 'dislikesfeed' %>
        </div>
        <%= will_paginate @dislikes, :page_links => false %>
      <% end %>
    <% end %>
    </td>
    
<% if signed_in? %>
    <% if is_mobile_view? %>
    <% else %>
    <td class="sidebar2 round">
      <%= render 'shared/user_info' %>
    </td>
    <% end %>
<% else %>
    <% if is_mobile_view? %>
    <% else %>
    <td class="sidebar2 round">
      <%= render 'shared/user_info_signedout' %>
    </td>
    <% end %>
<% end %>

  </tr>
</table>

app/views/users/dislikes.js.erb
$('#pages').append('<%= j render('dislikesfeed') %>');
<% if @dislikes.next_page %>
  $('.pagination').replaceWith('<%= j will_paginate(@dislikes) %>');
<% else %>
  $('.pagination').remove();
<% end %>
<% sleep 1 %>

app/views/users/index.html.erb
<h4>Stumweb: the front page of New York City!</h4>
</br>

<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
  <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/likes.js.erb
$('#pages').append('<%= j render('likesfeed') %>');
<% if @likes.next_page %>
  $('.pagination').replaceWith('<%= j will_paginate(@likes) %>');
<% else %>
  $('.pagination').remove();
<% end %>
<% sleep 1 %>

app/views/users/show.html.erb
<% if is_mobile_view? %>
  <table class="profile" summary="For signed-in users">
    <tr>
      <td class="main">
  <% else %>
  <table class="shadowborder">
    <tr>
      <td class="test">
  <% end %>
  
        <% if is_mobile_view? %>
      <h3>
        <span style="color:crimson"><%= @user.username %></span> <span style="color:mediumblue">Contents</span>
      </h3>
        <% else %>
      <h3 style="margin-left: 15px;">
        <span style="color:crimson"><%= @user.username %></span> <span style="color:mediumblue">Contents</span>
      </h3>
        <% end %>
    </br>

    <% if is_mobile_view? %>
        <% if @everything.any? %>
        <div>
          <%= render 'userfeed' %>
      </div>
        <%= will_paginate @everything, :page_links => false %>
      <% end %>
    <% else %>
        <% if @everything.any? %>
        <div id="pages" style="margin-left: 15px;">
          <%= render 'userfeed' %>
      </div>
        <%= will_paginate @everything, :page_links => false %>
      <% end %>
    <% end %>
    </td>

<% if signed_in? %>
    <% if is_mobile_view? %>
    <% else %>
    <td class="sidebar2 round">
      <%= render 'shared/user_info' %>
    </td>
    <% end %>
<% else %>
    <% if is_mobile_view? %>
    <% else %>
    <td class="sidebar2 round">
      <%= render 'shared/user_info_signedout' %>
    </td>
    <% end %>
<% end %>

  </tr>
</table>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>