config/routes.rb
Newstumweb::Application.routes.draw do

  resources :teams do
    resources :users
  end

  resources :users do
    get "new_message", :on => :collection
    post "create_message", :on => :collection
    delete "destroy_message", :on => :collection

    member do
      get 'likes'
      get 'dislikes'
      get 'messages'
      get 'inbox'
      get 'outbox'
      get 'show_message'
    end
  end

  resources :users do
    resources :comments
      end
  resources :sessions, :only => [:new, :create, :destroy]
  resources :photos do
    member do
      get 'like'
      get 'dislike'
    end
  end

  resources :password_resets

  resources :photos do
    resources :comments do
     get 'reply', :on => :collection
   end
 end

  resources :contents do
    member do
      get 'like'
      get 'dislike'
    end
  end

  resources :contents do
    resources :comments do
     get 'reply', :on => :collection
   end
 end

 resources :comments do
  member do
    get 'like'
    get 'dislike'
  end
end

  resources :photos do
    resources :captions 
  end

  root :to => "pages#home"

  match '/contact', :to => 'pages#contact'
  match '/about', :to => 'pages#about'
  match '/help', :to => 'pages#help'
  match '/contest', :to => 'pages#contest'
  match '/bestfeatures', :to => 'pages#bestfeatures'
  match '/index', :to => 'users#index'
  match '/signup', :to => 'users#new'
  match '/signin', :to => 'sessions#new'
  match '/sessions', :to => 'sessions#create'
  match '/signout', :to => 'sessions#destroy'
  match '/comments', :to => 'comments#create'
  match '/contents', :to => 'contents#index'
  match '/contents/:id', :to => 'contents#show'
  match '/contents/:content_id/comments', :to => 'comments#index'
  match '/photos/:photo_id/comments', :to => 'comments#index'
  match '/contents/:content_id/comments/reply', :to => 'comments#reply'
  match '/results', :to => 'contents#index'
  match '/newteam', :to => 'teams#new'
  match '/jointeam', :to => 'teams#join'

end

app/views/pages/about.html.erb
<% if is_mobile_view? %>
<h4 style="margin-left: 20px;"><span style="color:orangered">Stumweb</span><span style="color:mediumblue;">: the front page of New York City!</span></h4>
<% else %>
<h3 style="margin-left: 25px; width: 500px;"><span class="textshadow1" style="color:orangered; font-size: 120%;">Stumweb</span><span class="textshadow2" style="color:mediumblue; font-size: 95%;">: the front page of New York City!</span></h3>
<% end %>

<br>

<p style="margin-left: 25px;">Stumweb is the front page of New York City. New Yorkers can upload live statuses and pictures to make New York City come alive on the internet!</p>

app/views/pages/bestfeatures.html.erb
<% if is_mobile_view? %>
<h4 class="textshadow1" style="color: firebrick; font-size: 110%;">Best Features</h4>
<% else %>
<h4 class="textshadow1" style="color: firebrick; font-size: 160%;">Best features</h4>
<% end %>

<br>

In creating Stumweb.com, part of it was to see how far I can go and another part was to boost my resume. I will list the best features of my web app and explain the code behind them. Please share this page in case anyone you know is looking to hire an entry-level/junior Ruby on Rails developer that lives in New York City. I can be contacted at <a href="mailto:david.wu712@gmail.com">david.wu712@gmail.com</a>. Thank you!

<br>
<br>

Stumweb is written in ruby and uses Ruby on Rails, Twitter Bootstrap, Carrierwave plus MiniMagick, Amazon S3, Sendgrid using RoR ActionMailer, and hosted on Heroku.

<br>
<br>

<b>- The homepage news feed</b>

<br>
<br>

I have a pages controller with a home action that is the root_path to my app. In my home action, I have the following code:

<br>

<xmp>
@contents = Content.all
@photos = Photo.all
@everything = (@contents + @photos).sort_by(&:content_changed_at).reverse.paginate(page: params[:page], :per_page => 5) 
</xmp>

<br>

@contents and @photos relates to my Content and Photo models. I have a Comment model that when a content or photo gets commented on, it brings that content or photo to the top of the page. This is shown in @everything. In both my Content and Photo models, I have a :content_changed_at column which is a datetime. This column is the same as self.created_at when the object gets created and when a user comments on the content or photo, :content_changed_at will equal to the comment created_at time. I then sort @everything by this column and reverse it so @everything will have a descending order.

<br>
<br>

In my Content and Photo model, I have a before_create :init_sort_column callback and the code for :init_sort_column is:

<br>

<xmp>
def init_sort_column
  self.content_changed_at = self.created_at || Time.now
end 
</xmp>

<br>

Then in my Comment model, I have an after_create :update_parent_sort_column callback and the code for :update_parent_sort_column is

<br>

<xmp>
def update_parent_sort_column
  if self.commentable
    self.commentable.content_changed_at = self.created_at
    self.commentable.save
  end
end 
</xmp>

<br>

I have a polymorphic association between Content/Photo and Comment models and that is what self.commentable is.

<br>
<br>

In my view, the gist of my code is:

<br>

<xmp>
<%% @everything.each do |content| %>
  <%% if content.instance_of?(Content) %>
    <%% if (content.dislikes.count - content.likes.count) > 4 %>
      “This content is hidden because too many people think it's lame.”
    <%% else %>
      Code for content model.
    <%% end %>
  <%% elsif content.instance_of?(Photo) %>
    <%% if (content.dislikes.count - content.likes.count) > 4 %>
      “This photo is hidden because too many people think it's lame.”
    <%% else %>
    Code for photo model.
    <%% end %>
  <%% end %>
<%% end %>
</xmp> 

<br>

If the content/photo’s dislikes minus likes count is five or greater, I put the string “This content/photo is hidden because too many people think it's lame.”. This is to let users regulate my site to hide posts that they don’t like.

<br>
<br>          

I coupled this with <a href="http://railscasts.com/episodes/114-endless-page-revised">Railscasts episode 114</a> on endless pagination to create a seemingly endless scroll feature. 

<br>
<br>

<b>- The side navigations with browse past stories</b>

<br>
<br>

Using twitter bootstrap, here’s the css to fix the left and right side navigations to the page.

<br>

<xmp>
<div class="span2" style="position:fixed; left:0; width: 255px; padding-top: 10px;">
Basically the same code as the homepage, but I only show a content or photo if the dislikes minus likes count is 4 or less.
<%% if (content.dislikes.count - content.likes.count) < 5 %>
  Code for content/photo.
<%% end %>
</div>

<div class="span2" style="position:fixed; width:282px; right:0; padding-top: 10px;">
  Code for left side.
</div>
</xmp>

<br>

The span2 class refers to twitter bootstrap.

<br>
<br> 

For the browse past stories on the right side, I put a before_filter :load_side in my application controller and the code to :load_side is:

<br>

<xmp>
def load_side
  @user = current_user
  @contents = Content.all
  @photos = Photo.all
  @allcontents = (@contents + @photos).shuffle.last(2)
end 
</xmp>

<br>

<b>- User’s score and contest</b>

<br>
<br>

I added a :score column into the User model. The score for a user is calculated by 1 point each for the difference in all your posts’ likes count minus dislikes count plus 2 points each for each unique view on your post. 

<br>
<br>

In my Content and Photo models, I have an after_update :update_user_score and after_destroy :update_user_score callbacks where the code for :update_user_score is:

<br>

<xmp>
def update_user_score
  if self.user
    user = self.user
    everything = user.contents + user.photos
    likes_count = everything.inject(0) {|sum, f| sum + f.likes.count}
    dislikes_count = everything.inject(0) {|sum, f| sum + f.dislikes.count}
    unique_views = everything.inject(0) {|sum, f| sum + f.impressionist_count}
    score = ((2 * unique_views) + (likes_count - dislikes_count))
    user.update_column(:score, score)
  end
end 
</xmp>

<br>

I use the inject method on everything (user.contents + user.photos) to find the sum of all your contents and photos likes count, dislikes count, and unique views. Then I use these values to get the score and update the :score column of the user with the update_column method. To get unique views, I used the <a href="https://github.com/charlotte-ruby/impressionist">impressionist gem</a>.

<br>
<br>

I put a before_filter :top_three_users in my application controller and the code for :top_three_users is:

<br>

<xmp>
def top_three_users
  @topthreeusers = User.all.sort_by(&:score).reverse.first(3)
end 
</xmp>

<br>

I basically sort by the :score column, reverse it, and choose the first 3 to get the top three users.

<br>
<br>

In my view I put the following code to display the top three users:

<br>

<xmp>
<%% @topthreeusers.each do |user| %>
  <b><%%= user.username %></b>: <%%= user.score %>
  <br>
<%% end %>
</xmp>

<br>

<b>- Uploading photos along with a caption</b>

<br>
<br>

This feature took me a while to figure out. I first followed <a href="http://railscasts.com/episodes/253-carrierwave-file-uploads">Railscasts Ep. 253 CarrierWave File Uploads</a> to set up an Image Uploader to my Photo model. I use Amazon S3 to store the photos. In my image_uploader.rb file, I switched the storage to :fog and created a carrierwave.rb file in config/initializers folder. Put your Amazon S3 credentials there to allow Amazon to store your photos.

<br>
<br>

Another tricky part with allowing users to upload photos is that photos taken on mobile cameras can be sideways when you take the photo with your camera sideways. You can see them vertically on your camera because each photo has an exif data that can tell a whole bunch of details of your photo like the location, angle, type of camera, etc. and your camera will automatically format the photo by the angle in the exif data. 

<br>
<br>

To rotate these photos that were taken horizontally when uploading them to Amazon S3, I use MiniMagick by including this line of code in my image_uploader.rb file: 

<br>

<xmp>include CarrierWave::MiniMagick</xmp>

<br>

I also included the gem ‘mini_magick’ in my gemfile and bundle installed it.

<br>
<br>

Then in my image_uploader.rb file, I included the following code:

<br>

<xmp>
process :rotate

def rotate
  manipulate! do |image|
    image.auto_orient
    image
  end
end 
</xmp>

<br>

MiniMagick has a method called auto_orient which will rotate your photo if it was taken sideways by reading the exif data.

<br>
<br>

I also have a feature to create a caption with the photo when it is created. My Photo model has_many :captions along with an accepts_nested_attributes_for :captions and my Caption model belongs_to :photo. The problem to solve was trying to create two models at once in one form. 

<br>
<br>

The solution I used was in my view for the new action for my Photo model was:

<br>

<xmp>
<%%= simple_form_for(setup_content(current_user.photos.build(params[:photo]))) do |f| %>
  <%%= f.input :image_cache, :as => :hidden, label: false %>
  <%%= f.input :image, :as => :file, label: false %>
  <%%= f.input :remote_image_url, label: "or enter image URL", placeholder: 'Enter URL' %>
  <%%= f.simple_fields_for :captions do |b| %>
    <%%= b.input :body, :as => :text, label: 'Write a caption', placeholder: 'Enter a caption' %>
  <%% end %>
  <%%= f.submit "Submit Image", :class => 'btn btn-success' %>
<%% end %> 
</xmp>

<br>

Note: I use simple_form_for instead of the regular form_for. You can use this by using the <a href="https://github.com/plataformatec/simple_form">simple_form gem</a>.

<br>
<br>

I created a setup_content helper method in my helper file:

<br>

<xmp>
def setup_content(content)
  content.captions.build
  content
end 
</xmp>

<br>

This sets up the caption field once in the view.

<br>
<br>

In my simple_form_for I needed to use simple_fields_for :captions to create a caption along with creating the photo.

<br>
<br>

If any of you got any questions or want to know the code behind some feature I didn’t explain here, don’t hesitate to contact me at <a href="mailto:david.wu712@gmail.com">david.wu712@gmail.com</a>!

app/views/pages/contact.html.erb
<% if is_mobile_view? %>
<h4 style="margin-left: 20px;"><span style="color:orangered">Stumweb</span><span style="color:mediumblue;">: the front page of New York City!</span></h4>
<% else %>
<h3 style="margin-left: 25px; width: 500px;"><span class="textshadow1" style="color:orangered; font-size: 120%;">Stumweb</span><span class="textshadow2" style="color:mediumblue; font-size: 95%;">: the front page of New York City!</span></h3>
<% end %>
<br>

<p style="margin-left: 25px;">Email: contact@stumweb.com</p>

app/views/pages/contest.html.erb
<% if is_mobile_view? %>
<h4 style="margin-left: 20px;"><span style="color:orangered; font-size: 150%;">Stumweb</span><span style="color:mediumblue;">: the front page of New York City!</span></h4>
<% else %>
<h3 style="margin-left: 25px;"><span class="textshadow1" style="color:orangered; font-size: 120%;">Stumweb</span><span class="textshadow2" style="color:mediumblue;">: the front page of New York City!</span></h3>
<% end %>

<% if is_mobile_view? %>
<h4 class="textshadow1" style="color: firebrick; margin-left: 25px; font-size: 110%;">Three Highest Scoring Users Will Each Win an Amazon Kindle!</h4>
<% else %>
<h4 class="textshadow1" style="color: firebrick; margin-left: 25px; font-size: 160%;">Three Highest Scoring Users Will Each Win an Amazon Kindle!</h4>
<% end %>

<div style="margin-left: 25px;">
<h5 style="color: mediumblue; font-size: 115%">Contest Instructions</h5>
<span>1. <%= link_to "Sign up", signup_path %> as a new user. <b>Email is optional, but if you forget your password, your email is required to reset it.</b> You can always add your email later in your settings once signed in.</span>
<br>
<br>
<span>2. Start posting breaking updates, photos, reviews, upcoming events, etc. about New York City and watch your score go up!</span>  

<br>
<br>

<h5 style="color: mediumblue; font-size: 115%">Contest Rules</h5>
<span>1. Contest starts at 12:00am on Monday, February 11th, 2013 and will end at 11:59pm on Friday, April 12th, 2013.</span>
<br>
<br>
<span>2. The three highest scoring users will each win an <a href="http://www.amazon.com/Kindle-Ereader-ebook-reader/dp/B007HCCNJU">Amazon Kindle</a>.</span>
<br>
<br>
<span>3. Each user's score is calculated by 1 point each for the difference in all your posts’ likes count minus dislikes count (viral button is the same as like and lame button is the same as dislike) plus 2 points each for each unique view on your post.</span>
<br>
<br>
<span>4. An email is optional to sign up, but if you are one of the top three highest scoring users, <b>you will be required to add your email 48 hours after contest ends for Stumweb to contact you on how to receive your prize. If you have not added your email after 48 hours, the prize will be given to the next highest scoring user <u><i>with</i></u> an email.</b></span>
<br>
<br>
<span>6. Do not post any graphic, nude, disturbing, or offensive content. Stumweb reserves the right to delete any post that violates this rule as well as any future rules that arise.</span> 
</div>

app/views/pages/help.html.erb
<% if is_mobile_view? %>
<h4 style="margin-left: 20px;"><span style="color:orangered">Stumweb</span><span style="color:mediumblue;">: the front page of New York City!</span></h4>
<% else %>
<h3 style="margin-left: 25px; width: 500px;"><span class="textshadow1" style="color:orangered; font-size: 120%;">Stumweb</span><span class="textshadow2" style="color:mediumblue; font-size: 95%;">: the front page of New York City!</span></h3>
<% end %>
<br>

<p style="margin-left: 15px;">Help</p>

app/views/pages/home.html.erb
<!DOCTYPE html>

<% if signed_in? %>

  <% if is_mobile_view? %>
  <table class="profile" summary="For signed-in users">
    <tr>
      <td class="main">
  <% else %>
  <table class="shadowborder">
    <tr>
      <td class="test">
  <% end %>

        <% if is_mobile_view? %>
        <h4><span style="color:orangered; font-size: 150%;">Stumweb</span><span style="color:mediumblue; font-size: 115%;">: the front page of New York City!</span></h4>

        <br>

        <h4 style="font-size: 105%; color: darkblue">Three highest scoring users will each win an <span style="color: firebrick">Amazon Kindle</span>! <%= link_to "Click here", contest_path %> for more details.</h4>
        <% else %>
        <h3 style="margin-left: 15px; width: 500px;"><span class="textshadow1" style="color:orangered; font-size: 120%;">Stumweb</span><span class="textshadow2" style="color:mediumblue; font-size: 95%;">: the front page of New York City!</span></h3>

        <br>

        <h4 style="margin-left: 15px; width: 500px; color: mediumblue">Three highest scoring users will each win an <span style="color: firebrick">Amazon Kindle</span>! <%= link_to "Click here", contest_path %> for more details.</h4>
        <% end %>

      <% if is_mobile_view? %>

        
        <div class="bs-docs-example" style="font-size: 60%; width: 125%;">
            <ul class="nav nav-pills">
              <li class="dropdown">
                <a class="btn-custom3" class="dropdown-toggle" id="drop4" role="button" data-toggle="dropdown" href="#">What's up NYC?</a>
                <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
                  <%= simple_form_for(current_user.contents.build(params[:content])) do |f| %>
                    <%= f.input :content, as: :text, label: false, :placeholder => 'Create a message'%>
                    <%= f.submit "Submit Message", :class => 'btn btn-success' %>
                  <% end %>
                </ul>
              </li>
              <li class="dropdown">
                <a class="btn-custom3" class="dropdown-toggle" id="drop4" role="button" data-toggle="dropdown" href="#">Upload Image</a>
                <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
                  <%= render :file => '/photos/new' %>
                </ul>
              </li>
              </ul> <!-- /tabs -->
        </div>


    <% end %>

    <% if is_mobile_view? %>
    <div>
    <strong class="teamtitlecolor">Top Three Users</strong>
        <br>
        <% @topthreeusers.each do |user| %>
          <b><%= user.username %></b>: <%= user.score %>
          <br>
        <% end %>
        <%#= link_to "All users", users_path %>
        <br>
        <%= link_to "Contest details", contest_path %>
    </div>

<br>
        <div class="bs-docs-example" style="font-size: 60%; width: 125%;">
            <ul class="nav nav-pills">
              <li class="dropdown">
                <a class="btn-custominfomobile" class="dropdown-toggle" id="drop4" role="button" data-toggle="dropdown" href="#">My Info</a>
                <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
                   <strong>Likes count:</strong> <% everything = current_user.contents + current_user.photos  %>
                   <%= everything.inject(0) {|sum, f| sum + f.likes.count} %>
                   <br>
                   <strong>Dislikes count:</strong> <% everything = current_user.contents + current_user.photos  %>
                   <%= everything.inject(0) {|sum, f| sum + f.dislikes.count} %>
                   <br>
                   <strong>View count:</strong> <% everything = current_user.contents + current_user.photos  %>
                   <%= everything.inject(0) {|sum, f| sum + f.impressionist_count} %> 
                   <br>
                   <strong>Score:</strong> <%= current_user.score %>
                </ul>
              </li>
              <% if has_team? %>
              <li class="dropdown">
                <a class="btn-custominfomobile" class="dropdown-toggle" id="drop4" role="button" data-toggle="dropdown" href="#">Team Info</a>
                <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
                  <strong>Team:</strong> <%= current_user.team.team_name %>
                  <br>
                  <strong>Team score:</strong> <%= current_user.team.team_score %>
                  <br>
                  <br>
                  <% current_user.team.users.each do |mate| %>
                    <span style="color: mediumblue;"><%= link_to mate.username, mate, style: "padding: none; margin: none" %></span> <br>
                    <strong>Likes count:</strong> <% everything = mate.contents + mate.photos  %>
                    <%= everything.inject(0) {|sum, f| sum + f.likes.count} %>
                    <br>
                    <strong>Dislikes count:</strong> <% everything = mate.contents + mate.photos  %>
                    <%= everything.inject(0) {|sum, f| sum + f.dislikes.count} %>
                    <br>
                    <strong>View count:</strong> <% everything = mate.contents + mate.photos  %>
                    <%= everything.inject(0) {|sum, f| sum + f.impressionist_count} %> 
                    <br>
                    <strong>Score:</strong> <%= mate.score %>
                    <br>
                    <br>
                  <% end %>
                </ul>
              </li>
              <% end %>
              </ul> <!-- /tabs -->
          </div>
    <% end %>

<% if is_mobile_view? %>
<% else %>

<% end %>

<% if is_mobile_view? %>
        <% if @everything.any? %>
        <div>
        <%= render 'contents' %>  
        </div>
  <%= will_paginate @everything, :page_links => false %>
  <% end %>
<% else %>
        <% if @everything.any? %>
        <div id="pages" style="margin-left: 15px;">
        <%= render 'contents' %>  
        </div>
  <%= will_paginate @everything, :page_links => false %>
  <% end %>
<% end %>

      </td>
      <% if is_mobile_view? %>
      <% else %>
      <td class="sidebar2 round">
        <%= render 'shared/user_info' %>
      </td>
      <% end %>
    </tr>
  </table>

<% else %>

  <% if is_mobile_view? %>
  <table class="profile" summary="For signed-in users">
    <tr>
      <td class="main">
  <% else %>
  <table class="shadowborder">
    <tr>
      <td class="test">
  <% end %>

        <% if is_mobile_view? %>
        <h4><span style="color:orangered; font-size: 150%;">Stumweb</span><span style="color:mediumblue; font-size: 115%;">: the front page of New York City!</span></h4>

        <br>

        <h4 style="font-size: 105%; color: darkblue">Three highest scoring users will each win an <span style="color: firebrick">Amazon Kindle</span>! <%= link_to "Click here", contest_path %> for more details.</h4>
        <% else %>
        <h3 style="margin-left: 15px; width: 500px;"><span class="textshadow1" style="color:orangered; font-size: 120%;">Stumweb</span><span class="textshadow2" style="color:mediumblue; font-size: 95%;">: the front page of New York City!</span></h3>

        <br>
        
        <h4 style="margin-left: 15px; width: 500px; color: mediumblue">Join <span style="color:orangered">Stumweb</span> now and the three highest scoring users will each win an <span style="color: firebrick">Amazon Kindle</span>! <%= link_to "Click here", contest_path %> for more details.</h4>
        <% end %>

    <% if is_mobile_view? %>
        <div class="bs-docs-example" style="font-size: 60%; width: 125%;">
            <ul class="nav nav-pills">
              <li><%= link_to "What's up NYC?", signup_path, :class => "btn-custom3" %></li>
              <li><%= link_to "Upload Image", signup_path, :class => "btn-custom3" %></li>
            </ul> <!-- /tabs -->
        </div>
    <% end %>

    <% if is_mobile_view? %>
    <div>
    <strong class="teamtitlecolor">Top Three Users</strong>
        <br>
        <% @topthreeusers.each do |user| %>
          <b><%= user.username %></b>: <%= user.score %>
          <br>
        <% end %>
        <%= link_to "Contest details", contest_path %>
    </div>
    <% end %>

<br>

    <% if is_mobile_view? %>
    <% else %>
    
    <% end %>

<% if is_mobile_view? %>
        <% if @everything.any? %>
        <div>
        <%= render 'contents' %>  
        </div>
  <%= will_paginate @everything, :page_links => false %>
  <% end %>
<% else %>
        <% if @everything.any? %>
        <div id="pages" style="margin-left: 15px;">
        <%= render 'contents' %>  
        </div>
  <%= will_paginate @everything, :page_links => false %>
  <% end %>
<% end %>
  </td>
  
  <% if is_mobile_view? %>
  <% else %>
      <td class="sidebar2 round">
        <%= render 'shared/user_info_signedout' %>
      </td>
  <% end %>
    </tr>
</table>

<% end %>

app/views/pages/home.js.erb
$('#pages').append('<%= j render('contents') %>');
<% if @everything.next_page %>
  $('.pagination').replaceWith('<%= j will_paginate(@everything) %>');
<% else %>
  $('.pagination').remove();
<% end %>
<% sleep 1 %>

app/views/pages/rightside.html.erb
<h4>Past Stories</h4>
</br>


<% @everything.each do |content| %>

<% if content.instance_of?(Content) %>
<tr>
    <td class="gravatar">
    <%= link_to gravatar_for(content.user), content.user %>
  </td>
  <td class="micropost">
    <span class="content"><b><%= wrap(content.content.to_s) %></b></span>
    </br> 
    </br>
    <span class="timestamp">
      Posted <%= time_ago_in_words(content.created_at) %> ago by <%= link_to content.user.username, content.user %>
    </span>

    <ul class="nav nav-pills">
      <li><%= link_to pluralize(content.comments.count, "Comment"), content %></li>
      <% if signed_in? %>
    <li>
       <div class="dropdown">
    <a class="dropdown-toggle" data-toggle="dropdown" href="#">Reply</a>
    <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
        <%= form_for [content, current_user.comments.new] do |f| %>
      <%= render 'shared/error_messages', :object => f.object %>
    <div class="field">
    <%= f.text_area :body %>
    </div>
    <div class="actions">
    <%= f.submit "Submit" %>
    </div>
    <% end %>
    </ul>
    </div>
  </li>
  <% else %>
  <%= link_to "Reply", signin_path %>
  <% end %>
     <li><% user = content.user rescue User.find(content.user_id) %>
      <% if current_user?(user) %>
      <%= link_to "Delete", content, :method => :delete,
                                       :confirm => "Are you sure you want to delete this post?" %>
      <% end %></li>
</ul>
 
</td>
</tr>

<% elsif content.instance_of?(Photo) %>

<tr>
    <td class="gravatar">
    <%= link_to gravatar_for(content.user), content.user %>
  </td>
  <td class="micropost">
    <% if content.captions.any? %>
    <% content.captions.each do |caption| %>
    <span class="content"><b><%= wrap(caption.body) %></b></span>
    <% end %>
    </br>
    </br>
    <% end %>
    <span class="content"><%= image_tag content.image_url.to_s if content.image? %></span>
    </br> 
    </br>
    <span class="timestamp">
      Posted <%= time_ago_in_words(content.created_at) %> ago by <%= link_to content.user.username, content.user %>
    </span>

    <ul class="nav nav-pills">
      <li><%= link_to pluralize(content.comments.count, "Comment"), content %></li>
      <% if signed_in? %>
    <li>
       <div class="dropdown">
    <a class="dropdown-toggle" data-toggle="dropdown" href="#">Reply</a>
    <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
        <%= form_for [content, current_user.comments.new] do |f| %>
      <%= render 'shared/error_messages', :object => f.object %>
    <div class="field">
    <%= f.text_area :body %>
    </div>
    <div class="actions">
    <%= f.submit "Submit" %>
    </div>
    <% end %>
    </ul>
    </div>
  </li>
  <% else %>
  <%= link_to "Reply", signin_path %>
  <% end %>
     <li><% user = content.user rescue User.find(content.user_id) %>
      <% if current_user?(user) %>
      <%= link_to "Delete", content, :method => :delete,
                                       :confirm => "Are you sure you want to delete this post?" %>
      <% end %></li>
</ul>

</td>
</tr>

<% end %>
<% end %>

