config/routes.rb
Newstumweb::Application.routes.draw do

  resources :teams do
    resources :users
  end

  resources :users do
    get "new_message", :on => :collection
    post "create_message", :on => :collection
    delete "destroy_message", :on => :collection

    member do
      get 'likes'
      get 'dislikes'
      get 'messages'
      get 'inbox'
      get 'outbox'
      get 'show_message'
    end
  end

  resources :users do
    resources :comments
      end
  resources :sessions, :only => [:new, :create, :destroy]
  resources :photos do
    member do
      get 'like'
      get 'dislike'
    end
  end

  resources :password_resets

  resources :photos do
    resources :comments do
     get 'reply', :on => :collection
   end
 end

  resources :contents do
    member do
      get 'like'
      get 'dislike'
    end
  end

  resources :contents do
    resources :comments do
     get 'reply', :on => :collection
   end
 end

 resources :comments do
  member do
    get 'like'
    get 'dislike'
  end
end

  resources :photos do
    resources :captions 
  end

  root :to => "pages#home"

  match '/contact', :to => 'pages#contact'
  match '/about', :to => 'pages#about'
  match '/help', :to => 'pages#help'
  match '/contest', :to => 'pages#contest'
  match '/bestfeatures', :to => 'pages#bestfeatures'
  match '/index', :to => 'users#index'
  match '/signup', :to => 'users#new'
  match '/signin', :to => 'sessions#new'
  match '/sessions', :to => 'sessions#create'
  match '/signout', :to => 'sessions#destroy'
  match '/comments', :to => 'comments#create'
  match '/contents', :to => 'contents#index'
  match '/contents/:id', :to => 'contents#show'
  match '/contents/:content_id/comments', :to => 'comments#index'
  match '/photos/:photo_id/comments', :to => 'comments#index'
  match '/contents/:content_id/comments/reply', :to => 'comments#reply'
  match '/results', :to => 'contents#index'
  match '/newteam', :to => 'teams#new'
  match '/jointeam', :to => 'teams#join'

end

app/views/layouts/_footer.html.erb
footer>
  <nav class="round">
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
   <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Stumweb</a>
          <div class="nav-collapse collapse">
            <ul class="nav">
              <li class="active"><%= link_to "Home", root_path %></li>
              <li><%= link_to "About", about_path %></li>
              <li><%= link_to "Contact", contact_path %></li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li><a href="#">Action</a></li>
                  <li><a href="#">Another action</a></li>
                  <li><a href="#">Something else here</a></li>
                  <li class="divider"></li>
                  <li class="nav-header">Nav header</li>
                  <li><a href="#">Separated link</a></li>
                  <li><a href="#">One more separated link</a></li>
                </ul>
              </li>
            </ul>
            <form class="navbar-search pull-left">
            <input type="text" class="search-query" placeholder="Search">
          </form>
            <form class="navbar-form pull-right">
              <input class="span2" type="text" placeholder="Username">
              <input class="span2" type="password" placeholder="Password">
              <button type="submit" class="btn">Sign in</button>
            </form>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>
</header>

app/views/layouts/_header2.html.erb
<header>
  <%= link_to "Stumweb", root_path %>
  <nav class="round">
    <ul>
      <li><%= link_to "Home", root_path %></li>
      <% # if signed_in? %>
        <li><%= link_to "Profile", # current_user %></li>
        <li><%= link_to "Users", # users_path %></li>
        <li><%= link_to "Settings", # edit_user_path(current_user) %></li>
      <% # end %>
      <li><%= link_to "Help", help_path %></li>
      <% # if signed_in? %>
        <li><%= link_to "Sign out", # signout_path %></li>
      <% # else %>
            <%= link_to "Sign up now!", # signup_path %>
        <li><%= link_to "Sign in", # signin_path %></li>
      <% # end %>
    </ul>
  </nav>
</header>

              <li><%= link_to "Profile", # %></li>
              <li><%= link_to "Users", # %></li>

                           <li><%= link_to "Settings", # %></li>

app/views/layouts/_header3.html.erb
<% if is_mobile_view? %>

<header style="margin: 0px; padding: 0px; width: 105%;">
   <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <div class="nav-collapse collapse">
            <% if signed_in? %>
            <ul class="nav">
              &#160; &#160; &#160; 
              <%= link_to "Home", root_path, :style => "color:white" %> &#160; &#160;
              <%= link_to "Profile", current_user, :style => "color:white" %> &#160; &#160;
              <%= link_to "Sign out", signout_path, :style => "color:white" %> &#160; &#160;
            <form class="navbar-search pull-right" method="get" action="http://www.picosearch.com/cgi-bin/ts.pl">
              <input type="hidden" name="index" value="526045" />
              &#160; &#160; <input type="text" name="query" class="search-query" style="width: 55%;" placeholder="Search">
              <td><span style="white-space: nowrap;"><input type="submit" value="Go" name="search" /></span></td>
            </form>
            </ul>
            <% else %>
            <ul class="nav">
              &#160; &#160; &#160; 
              <%= link_to "Home", root_path, :style => "color:white" %> &#160; &#160;
              <%= link_to "Sign up!", signup_path, :style => "color:white" %> &#160; &#160;
              <%= link_to "Sign in", signin_path, :style => "color:white" %> &#160; &#160;
            <form class="navbar-search pull-right" method="get" action="http://www.picosearch.com/cgi-bin/ts.pl">
              <input type="hidden" name="index" value="526045" />
              &#160; &#160; <input type="text" name="query" class="search-query" style="width: 50%;" placeholder="Search">
              <td><span style="white-space: nowrap;"><input type="submit" value="Go" name="search" /></span></td>
            </form>
            </ul> 
            <% end %>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>
</header>

<% else %>

<header>
   <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <%= link_to "Stumweb", root_path, :class => "brand" %>
          <div class="nav-collapse collapse">
            <ul class="nav">
              <li class="active"><%= link_to "Home", root_path %></li>
              <% if signed_in? %>
              <li><%= link_to "Profile", current_user %></li>

              <% end %>

              <% if signed_in? %>
              <li><%= link_to "Sign out", signout_path %></li>
              <% end %>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">More<b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li><%= link_to "About", about_path %></li>
                  <li><%= link_to "Contact", contact_path %></li>
                  <li><%#= link_to "Help", help_path %></li>
                  <% if signed_in? %>
                  <li class="divider"></li>
                  <li class="nav-header">Options</li>
                  <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                  <% end %>
                </ul>
              </li>
            </ul>
            <ul class="nav">
            <% if signed_in? %>
            <form class="navbar-search pull-right" method="get" action="http://www.picosearch.com/cgi-bin/ts.pl">
              <input type="hidden" name="index" value="526045" />
              <input type="text" name="query" class="search-query" placeholder="Search">
              <td><span style="white-space: nowrap;"><input type="submit" value="Go" name="search" /></span></td></tr>
            </form>
            <% end %>
            <% if signed_out? %>
            <li><%= link_to "Sign up!", signup_path %></li>
             <ul class="nav pull-left">
              <li class="dropdown">
            <a class="dropdown-toggle" href="#" data-toggle="dropdown">Sign In <strong class="caret"></strong></a>
            <div class="dropdown-menu" style="padding: 15px; padding-bottom: 0px;">
            <%= form_for(:sessions, :url => sessions_path, :class => "navbar-form pull-left") do |f| %>
              <li><%= f.text_field :username, :placeholder => "Username", :class => "span2"%></li>
              <li><%= f.password_field :password, :placeholder => "Password", :class => "span2"%></li>
              <li><%= f.submit "Sign in", :class => "btn btn-primary"%></li>
              <br>
              <li style="margin-left: -20px;"><%= link_to "Forgot password?", new_password_reset_path %></li>
            <% end %>
            </div>
              </li>
            </ul>
            <% end %>
            <% if signed_out? %>
            <form class="navbar-search pull-right" method="get" action="http://www.picosearch.com/cgi-bin/ts.pl">
              <input type="hidden" name="index" value="526045" />
              <input type="text" name="query" class="search-query" placeholder="Search">
              <td><span style="white-space: nowrap;"><input type="submit" value="Go" name="search" /></span></td></tr>
            </form>
            <% end %>
            </ul> 
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>
</header>

<% end %>

app/views/layouts/_header4.html.erb
<header>
   <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <%= link_to "Stumweb", root_path, :class => "brand" %>
          <div class="nav-collapse collapse">
            <ul class="nav">
              <li class="active"><%= link_to "Home", root_path %></li>
              <% if signed_in? %>
              <li><%= link_to "Profile", current_user %></li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Messages<b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Inbox", inbox_user_path(current_user) %></li>
                  <li><%= link_to "Sent", outbox_user_path(current_user) %></li>
                </ul>
              </li>
              <% end %>
              <li><%= link_to "Users", users_path %></li>
              <% if signed_in? %>
              <li><%= link_to "Sign out", signout_path %></li>
              <% end %>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">More<b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li><%= link_to "About", about_path %></li>
                  <li><%= link_to "Contact", contact_path %></li>
                  <li><%= link_to "Help", help_path %></li>
                  <% if signed_in? %>
                  <li class="divider"></li>
                  <li class="nav-header">Options</li>
                  <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                  <% end %>
                </ul>
              </li>
            </ul>
            <ul class="nav">
            <% if signed_in? %>
            <form class="navbar-search pull-right">
              <input type="text" class="search-query" placeholder="Search">
              <button type="submit" class="btn">Go</button>
            </form>
            <% end %>
            <% if signed_out? %>
            <li><%= link_to "Sign up!", signup_path %></li>
             <ul class="nav pull-left">
              <li class="dropdown">
            <a class="dropdown-toggle" href="#" data-toggle="dropdown">Sign In <strong class="caret"></strong></a>
            <div class="dropdown-menu" style="padding: 15px; padding-bottom: 0px;">
            <%= form_for(:sessions, :url => sessions_path, :class => "navbar-form pull-left") do |f| %>
              <li><%= f.text_field :username, :placeholder => "Username", :class => "span2"%></li>
              <li><%= f.password_field :password, :placeholder => "Password", :class => "span2"%></li>
              <li><%= f.submit "Sign in", :class => "btn btn-primary"%></li>
            <% end %>
            </div>
              </li>
            </ul>
            <% end %>
            <% if signed_out? %>
            <form class="navbar-search pull-right">
              <input type="text" class="search-query" placeholder="Search">
              <button type="submit" class="btn">Go</button>
            </form>
            <% end %>
            </ul> 
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>
</header>

app/views/layouts/_header5.html.erb
<header>
   <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <%= link_to "Stumweb", root_path, :class => "brand" %>
          <div class="nav-collapse collapse">
            <ul class="nav">
              <li class="active"><%= link_to "Home", root_path %></li>
              <% if signed_in? %>
              <li><%= link_to "Profile", current_user %></li>

              <% end %>

              <% if signed_in? %>
              <li><%= link_to "Sign out", signout_path %></li>
              <% end %>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">More<b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li><%= link_to "About", about_path %></li>
                  <li><%= link_to "Contact", contact_path %></li>
                  <li><%= link_to "Help", help_path %></li>
                  <% if signed_in? %>
                  <li class="divider"></li>
                  <li class="nav-header">Options</li>
                  <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                  <% end %>
                </ul>
              </li>
            </ul>
            <ul class="nav">
            <% if signed_in? %>
            <form class="navbar-search pull-right">
              <input type="text" class="search-query" placeholder="Search">
              <button type="submit" class="btn">Go</button>
            </form>
            <% end %>
            <% if signed_out? %>
            <li><%= link_to "Sign up!", signup_path %></li>
             <ul class="nav pull-left">
              <li class="dropdown">
            <a class="dropdown-toggle" href="#" data-toggle="dropdown">Sign In <strong class="caret"></strong></a>
            <div class="dropdown-menu" style="padding: 15px; padding-bottom: 0px;">
            <%= form_for(:sessions, :url => sessions_path, :class => "navbar-form pull-left") do |f| %>
              <li><%= f.text_field :username, :placeholder => "Username", :class => "span2"%></li>
              <li><%= f.password_field :password, :placeholder => "Password", :class => "span2"%></li>
              <li><%= f.submit "Sign in", :class => "btn btn-primary"%></li>
            <% end %>
            </div>
              </li>
            </ul>
            <% end %>
            <% if signed_out? %>
            <form class="navbar-search pull-right">
              <%= form_tag contents_path, method: :get do %>
                  <%= text_field_tag :search, params[:search] %>
                  <%= submit_tag "Search", name: nil %>
              <% end %>
            </form>
            <% end %>
            </ul> 
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>
</header>

app/views/layouts/_sidenav.html.erb
<div class="span2" style="position:fixed; left:0; width: 255px; padding-top: 10px;">
  <div class="shadowborderleft">
  	<div style="margin-left: 15px; margin-bottom: 1000px;">
<% if signed_in? %>

 

	<h3 class="title" style="color:mediumblue;">What's up?</h3>
    <%= render 'shared/content_form' %>

   	<h3 class="title" style="color:mediumblue;">Upload an Image</h3>
    <%= render :file => '/photos/new' %>

  

<% else %>

    <h1 class="title" style="color:mediumblue;">New user?</h1> 
            <ul class="nav nav-pills" style="font-size: 85%;">
              <li><%= link_to "Sign up now!", signup_path, :class => "btn-customsignup" %> </li>
            </ul> <!-- /tabs -->
          <%= link_to "(Email optional) It takes less than a minute. I promise.", signup_path, :class => "lead" %>
      
<br>
<br>
    <h1 class="title" style="color:mediumblue;">Already have an account?</h1> 
    <ul class="nav nav-pills" style="font-size: 85%;">
    	<li><%= link_to "Sign in now!", signin_path, :class => "btn-customsignup" %></li>
      <br>
      <br>
      <li style="font-size: 150%; margin-left: -13px;"><%= link_to "Forgot password?", new_password_reset_path %></li>   
    </ul>
<% end %>
</div>
</div>
</div>


<div id="sidebar" class="span2" style="position:fixed; width:282px; right:0; padding-top: 10px;">
	<div class="shadowborderright">
	  <div style="margin-left: 15px; margin-bottom: 1000px; margin-top: 17px;">
<%= render 'shared/rightside' %>
		</div>
	</div> 
</div>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag    "bootstrap2.css", :media => "all" %>
<%= stylesheet_link_tag    "custom.css", :media => "all" %>
<% if is_mobile_view? %>
<%= stylesheet_link_tag    "bootstrap-responsive.css", :media => "all" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html xmlns:fb="http://ogp.me/ns/fb#">
<head>
  <title><%= title %></title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"> 
  <%= csrf_meta_tags %>
  <%= render 'layouts/stylesheets' %>
  <%= javascript_include_tag "application.js" %>
  <%= javascript_include_tag "bootstrap.js" %>
</head>
<body>
  <div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

<% if is_mobile_view? %>
  <div class="container-fluid">
    <%= render 'layouts/header3' %>
    <style type="text/css">
      body {
        background: #fcfcfc;
        position: absolute;
        font-size: 125%;
        padding-top: 0px;
        margin: 0px;
        padding-bottom: 0px;
      }
    </style>
    <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    </div>
<% else %>
	<div class="container">
    <%= render 'layouts/header3' %>
    <%= render 'layouts/sidenav' %>
    <style type="text/css">
      body {
        background: #fcfcfc;
        position: absolute;
        left: 21.5%;
        padding-top: 60px;
        padding-bottom: 40px;
      }
    </style>
		<%= yield %>
      <%#= debug(params) if Rails.env.development? %>
    </div>
<% end %>
</body>
</html>

app/views/layouts/application2.html.erb
<!DOCTYPE html>
<html xmlns:fb="http://ogp.me/ns/fb#">
<head>
  <title><%= title %></title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"> 
  <%= csrf_meta_tags %>
  <%= render 'layouts/stylesheets' %>
  <%= javascript_include_tag "application.js" %>
  <%= javascript_include_tag "bootstrap.js" %>
</head>
<body>
  <div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

<% if is_mobile_view? %>
  <div class="container-fluid">
    <%= render 'layouts/header3' %>
    <style type="text/css">
      body {
        background: #fcfcfc;
        position: absolute;
        font-size: 125%;
        padding-top: 0px;
        margin: 0px;
        padding-bottom: 0px;
      }
    </style>
    <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    </div>
<% else %>
  <div class="container">
    <%= render 'layouts/header3' %>
    <style type="text/css">
      body {
        background: #fcfcfc;
        position: absolute;
        left: 21.5%;
        padding-top: 60px;
        padding-bottom: 40px;
      }
    </style>
    <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    </div>
<% end %>
</body>
</html>

app/views/layouts/sidenav.html.erb
<div class="span2" style="position:fixed; left:0">  
<% if signed_in? %>
	<h1 class="micropost">What's up?</h1>
    <%= render 'shared/content_form' %>

   	<h1 class="Photo">Upload a Photo</h1>
    <%= render 'shared/content_image_form' %>
<% end %>


</div>
<div class="span2" style="position:fixed; right:0">  
CONTENT 
</div>